export * from './diffTableController.service';
import { DiffTableControllerService } from './diffTableController.service';
export * from './dpListenController.service';
import { DpListenControllerService } from './dpListenController.service';
export * from './fileController.service';
import { FileControllerService } from './fileController.service';
export * from './jwtAuthenticationController.service';
import { JwtAuthenticationControllerService } from './jwtAuthenticationController.service';
export * from './taskController.service';
import { TaskControllerService } from './taskController.service';
export const APIS = [DiffTableControllerService, DpListenControllerService, FileControllerService, JwtAuthenticationControllerService, TaskControllerService];
