/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { DiffTableDTO } from '../model/diffTableDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DiffTableControllerService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * deletediffTable
     * 
     * @param difftableid difftableid
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deletediffTableUsingDELETE(difftableid: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deletediffTableUsingDELETE(difftableid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deletediffTableUsingDELETE(difftableid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deletediffTableUsingDELETE(difftableid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (difftableid === null || difftableid === undefined) {
            throw new Error('Required parameter difftableid was null or undefined when calling deletediffTableUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/difftable/${encodeURIComponent(String(difftableid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getDiffTable
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDiffTableUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<DiffTableDTO>>;
    public getDiffTableUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DiffTableDTO>>>;
    public getDiffTableUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DiffTableDTO>>>;
    public getDiffTableUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<DiffTableDTO>>(`${this.basePath}/difftable`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getdiffTables
     * 
     * @param difftableid difftableid
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getdiffTablesUsingGET(difftableid: number, observe?: 'body', reportProgress?: boolean): Observable<DiffTableDTO>;
    public getdiffTablesUsingGET(difftableid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DiffTableDTO>>;
    public getdiffTablesUsingGET(difftableid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DiffTableDTO>>;
    public getdiffTablesUsingGET(difftableid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (difftableid === null || difftableid === undefined) {
            throw new Error('Required parameter difftableid was null or undefined when calling getdiffTablesUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<DiffTableDTO>(`${this.basePath}/difftable/${encodeURIComponent(String(difftableid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * savediffTable
     * 
     * @param difftableDTO difftableDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public savediffTableUsingPOST(difftableDTO: DiffTableDTO, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public savediffTableUsingPOST(difftableDTO: DiffTableDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public savediffTableUsingPOST(difftableDTO: DiffTableDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public savediffTableUsingPOST(difftableDTO: DiffTableDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (difftableDTO === null || difftableDTO === undefined) {
            throw new Error('Required parameter difftableDTO was null or undefined when calling savediffTableUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<string>(`${this.basePath}/difftable`,
            difftableDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update
     * 
     * @param difftableDTO difftableDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateUsingPUT(difftableDTO: DiffTableDTO, observe?: 'body', reportProgress?: boolean): Observable<DiffTableDTO>;
    public updateUsingPUT(difftableDTO: DiffTableDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DiffTableDTO>>;
    public updateUsingPUT(difftableDTO: DiffTableDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DiffTableDTO>>;
    public updateUsingPUT(difftableDTO: DiffTableDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (difftableDTO === null || difftableDTO === undefined) {
            throw new Error('Required parameter difftableDTO was null or undefined when calling updateUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<DiffTableDTO>(`${this.basePath}/difftable`,
            difftableDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
