/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { TaskMainDTO } from '../model/taskMainDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TaskControllerService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * deletetaskmain
     * 
     * @param taskmainid taskmainid
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deletetaskmainUsingDELETE(taskmainid: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deletetaskmainUsingDELETE(taskmainid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deletetaskmainUsingDELETE(taskmainid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deletetaskmainUsingDELETE(taskmainid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (taskmainid === null || taskmainid === undefined) {
            throw new Error('Required parameter taskmainid was null or undefined when calling deletetaskmainUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/taskmain/${encodeURIComponent(String(taskmainid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getTasknain
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTasknainUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<TaskMainDTO>>;
    public getTasknainUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TaskMainDTO>>>;
    public getTasknainUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TaskMainDTO>>>;
    public getTasknainUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<TaskMainDTO>>(`${this.basePath}/taskmain`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * gettaskmains
     * 
     * @param taskmainid taskmainid
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public gettaskmainsUsingGET(taskmainid: number, observe?: 'body', reportProgress?: boolean): Observable<TaskMainDTO>;
    public gettaskmainsUsingGET(taskmainid: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TaskMainDTO>>;
    public gettaskmainsUsingGET(taskmainid: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TaskMainDTO>>;
    public gettaskmainsUsingGET(taskmainid: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (taskmainid === null || taskmainid === undefined) {
            throw new Error('Required parameter taskmainid was null or undefined when calling gettaskmainsUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<TaskMainDTO>(`${this.basePath}/taskmain/${encodeURIComponent(String(taskmainid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * savetaskmain
     * 
     * @param dpListenDTO dpListenDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public savetaskmainUsingPOST(dpListenDTO: TaskMainDTO, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public savetaskmainUsingPOST(dpListenDTO: TaskMainDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public savetaskmainUsingPOST(dpListenDTO: TaskMainDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public savetaskmainUsingPOST(dpListenDTO: TaskMainDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (dpListenDTO === null || dpListenDTO === undefined) {
            throw new Error('Required parameter dpListenDTO was null or undefined when calling savetaskmainUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<number>(`${this.basePath}/taskmains`,
            dpListenDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update
     * 
     * @param dpListenDTO dpListenDTO
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateUsingPUT2(dpListenDTO: TaskMainDTO, observe?: 'body', reportProgress?: boolean): Observable<TaskMainDTO>;
    public updateUsingPUT2(dpListenDTO: TaskMainDTO, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TaskMainDTO>>;
    public updateUsingPUT2(dpListenDTO: TaskMainDTO, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TaskMainDTO>>;
    public updateUsingPUT2(dpListenDTO: TaskMainDTO, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (dpListenDTO === null || dpListenDTO === undefined) {
            throw new Error('Required parameter dpListenDTO was null or undefined when calling updateUsingPUT2.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<TaskMainDTO>(`${this.basePath}/taskmains`,
            dpListenDTO,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
